spring.application.name=DTQ

# Redis Server Connection
spring.data.redis.host=localhost
spring.data.redis.port=8080
# spring.data.redis.password=your_password_here 

# Redis Pool Settings
spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-idle=8
spring.data.redis.lettuce.pool.min-idle=2

